### PR TITLE
Fixed Discords "The application did not respond" error

### PR DESCRIPTION
**Pull request by OnSive**
If the app needs more than 3 seconds to respond to slash commands, the error "The application did not respond" is thrown.

You can work around the error by responding directly with a loading message and then modify the original after the data was pulled.

Additionally: made the respond messages as "Only you can see this" messages to not spam other people. Can be rolled back if you don't like the idea (it's the `ephemeral: true` parameter in `await RespondAsync(embed: builder.Build(), ephemeral: true);`).

### CODE REVIEW

**Comment by OnSive** [comment]
@MatrikMoon don't know if the bot is even actively developed, but here is a pull request :)

**Comment by MatrikMoon** [comment]
It is soon to be replaced, but I'll take all the help I can get! Thanks for the work! I'll test it when I am home from vacation

**Comment by OnSive** [comment]
Have a great vacation!
Don't even want to bother you more, but what can we expect to come as replacement?

**Review by MatrikMoon — APPROVED** [review]

**Comment by MatrikMoon** [comment]
<3
Sorry it took me so long to get back- likely it'll be built into the next "Coordinator Panel" once I get that done. Unfortunately quite a while a way, I think

**Pull request merged**
